version: '3.8'
services:
  rssh:
    image: shourai/docker-rssh
    container_name: rssh
    environment:
      - username=canary
    volumes:
      - ./data:/home/canary
    ports:
      - "2222:22"
    restart: always
